### ISSUE TITLE
v0.1.0 TODO

### ISSUE THREAD

**Issue by CovId111** [CovId111/SCPM#6]
- [ ] [`db.rs`] Добавление пакетов в БД.
- [ ] [`cursive.rs`] Добавление окна для просмотра сведений о пакете.
- [ ] [`install.rs`] Добавление модуля для установки пакета в систему.
	- [ ] `download()` - скачивание пакета из онлайн-репозиториев.
	- [ ] `chmod()` - установка права исполнения скачанному пакету.
	- [ ] `copy()` - копирование пакета в `BINDIR`.
	- [ ] `integrate()` - установка файлов `*.png` и `*.desktop` в систему.
	- [ ] Добавление пакета в таблицу `packages_installed`.
- [ ] [`cursive.rs`] Добавление окна для установки пакета в систему.
- [ ] [`remove.rs`] Добавление модуля для удаления пакета из системы
	- [ ] `rmbin()` - удаление пакета из системы.
	- [ ] `rmdesktop()` - удаление `*.desktop` из системы.
	- [ ] `rmicon()` - удаление `*.png` из системы.
	- [ ] `rmdb()` - удаление пакета из базы данных.
